### ISSUE TITLE
Hit points set to NaN when editing them without supplying a value

### ISSUE THREAD

**Issue by woutermeuwis** [Brammm/dnd-encounter-tracker#1]
If no value is supplied when the heal or damage button is clicked, the current HP value sets to `Not a Number`, and can no longer be edited.

It would make more sense to validate that a value has been provided before executed teh heal/dmg action

![image](https://github.com/Brammm/dnd-encounter-tracker/assets/15607234/a60d604d-6049-4ac3-a9d3-a6ac468bbd4a)

**Comment by Brammm** [comment]
Fixed in latest version
